apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: hello-gw
  namespace: hello
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: ["*"]
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-vs
  namespace: hello
spec:
  hosts: ["*"]
  gateways: ["hello-gw"]
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: hello-world.hello.svc.cluster.local
        port:
          number: 80
