apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.22.3        # pin a version you want
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
    createNamespace: true
  syncPolicy:
    automated: { prune: true, selfHeal: true }