apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istiod
    targetRevision: 1.22.3
    helm:
      values: |
        meshConfig:
          accessLogFile: /dev/stdout
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
    createNamespace: true
  syncPolicy:
    automated: { prune: true, selfHeal: true }
