apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.85.0
    helm:
      values: |
        auth:
          strategy: anonymous
        deployment:
          service_type: NodePort
          nodeport_port: 32001       # => http://127.0.0.1:32001
        external_services:
          prometheus:
            url: http://prometheus-server.monitoring.svc.cluster.local
          grafana:
            enabled: false   
          tracing:
            enabled: true   
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
    createNamespace: true
  syncPolicy:
    automated: { prune: true, selfHeal: true }
