apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://kiali.org/helm-charts
    chart: kiali-server
    targetRevision: 1.85.0
    helm:
      values: |
        auth:
          strategy: anonymous
        external_services:
          prometheus:
            url: http://prometheus-server.monitoring.svc.cluster.local
        deployment:
          accessible_namespaces: ["**"]   # show all; restrict later if you want
        server:
          web_fqdn: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
